[package]
name = "scent-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "scent"
path = "src/main.rs"

[dependencies]
scent-config = { path = "../scent-config" }
scent-core = { path = "../scent-core" }
scent-domain = { path = "../scent-domain" }
scent-metrics = { path = "../scent-metrics" }
scent-report = { path = "../scent-report" }
scent-rules = { path = "../scent-rules" }

[lints]
workspace = true
