[package]
name = "scent-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
scent-domain = { path = "../scent-domain" }
scent-graph = { path = "../scent-graph" }
scent-ir = { path = "../scent-ir" }
scent-parser = { path = "../scent-parser" }

[lints]
workspace = true
