# PowerShell tab-completion for the `scent` CLI.
#
# Same limitation as scent.bash: SCENT's argument parser is hand-rolled,
# not generated by a framework, so this only completes command and flag
# *names* — it does not know which flags belong to which command, and it
# does not suggest file paths (PowerShell's own path completion already
# handles <path>).
#
# Install for this session only, from the scent/ directory:
#   . completions/scent.ps1
#
# Install permanently: add this to your PowerShell profile ($PROFILE),
# with the real absolute path to this file (a relative path won't resolve
# once the profile runs from a different directory):
#   . C:\absolute\path\to\scent\completions\scent.ps1

Register-ArgumentCompleter -Native -CommandName scent -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    $previous = if ($tokens.Count -ge 2) { $tokens[-2] } else { $null }

    if ($previous -eq '--format') {
        'human', 'json', 'sarif', 'table' |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
        return
    }

    if ($tokens.Count -le 2) {
        'analyze', 'rules', 'gate', '--help', '-h' |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
        return
    }

    '--format', '--max-critical', '--max-high', '--baseline', '--help', '-h' |
        Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
