[workspace]
members = [
    "crates/scent-cli",
    "crates/scent-core",
    "crates/scent-domain",
    "crates/scent-ir",
    "crates/scent-parser",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
